Include.pcm_split.File "/common/pcm/split.conf"

Macro [
	{
		SplitPCM {
			Name "yamaha_urx44_stereo_out"
			Direction Playback
			Channels 2
			HWChannels 18
			HWChannelPos0 FL  # USB MAIN A Left
			HWChannelPos1 FR  # USB MAIN A Right
			HWChannelPos2 FL  # USB MAIN B Left
			HWChannelPos3 FR  # USB MAIN B Right
			HWChannelPos4 FL  # USB MAIN C Left
			HWChannelPos5 FR  # USB MAIN C Right
		}
	}
	{
		SplitPCM {
			Name "yamaha_urx44_stereo_in"
			Direction Capture
			Channels 2
			HWChannels 18
			HWChannelPos0 FL  # USB MAIN A Left
			HWChannelPos1 FR  # USB MAIN A Right
			HWChannelPos2 FL  # USB MAIN B Left
			HWChannelPos3 FR  # USB MAIN B Right
			HWChannelPos4 FL  # USB MAIN C Left
			HWChannelPos5 FR  # USB MAIN C Right
		}
	}
]

SectionDevice."Line1" {
	Comment "USB MAIN A"

	Value {
		PlaybackPriority 120
	}
	Macro.pcm_split.SplitPCMDevice {
		Name "yamaha_urx44_stereo_out"
		Direction Playback
		HWChannels 18
		Channels 2
		Channel0 0
		Channel1 1
		ChannelPos0 FL
		ChannelPos1 FR
	}
}

SectionDevice."Line2" {
	Comment "USB MAIN B"

	Value {
		PlaybackPriority 110
	}
	Macro.pcm_split.SplitPCMDevice {
		Name "yamaha_urx44_stereo_out"
		Direction Playback
		HWChannels 18
		Channels 2
		Channel0 2
		Channel1 3
		ChannelPos0 FL
		ChannelPos1 FR
	}
}

SectionDevice."Line3" {
	Comment "USB MAIN C"

	Value {
		PlaybackPriority 100
	}
	Macro.pcm_split.SplitPCMDevice {
		Name "yamaha_urx44_stereo_out"
		Direction Playback
		HWChannels 18
		Channels 2
		Channel0 4
		Channel1 5
		ChannelPos0 FL
		ChannelPos1 FR
	}
}

SectionDevice."Line4" {
	Comment "USB MAIN A"

	Value {
		CapturePriority 120
	}
	Macro.pcm_split.SplitPCMDevice {
		Name "yamaha_urx44_stereo_in"
		Direction Capture
		HWChannels 18
		Channels 2
		Channel0 0
		Channel1 1
		ChannelPos0 FL
		ChannelPos1 FR
	}
}

SectionDevice."Line5" {
	Comment "USB MAIN B"

	Value {
		CapturePriority 110
	}
	Macro.pcm_split.SplitPCMDevice {
		Name "yamaha_urx44_stereo_in"
		Direction Capture
		HWChannels 18
		Channels 2
		Channel0 2
		Channel1 3
		ChannelPos0 FL
		ChannelPos1 FR
	}
}

SectionDevice."Line6" {
	Comment "USB MAIN C"

	Value {
		CapturePriority 100
	}
	Macro.pcm_split.SplitPCMDevice {
		Name "yamaha_urx44_stereo_in"
		Direction Capture
		HWChannels 18
		Channels 2
		Channel0 4
		Channel1 5
		ChannelPos0 FL
		ChannelPos1 FR
	}
}